// Code generated by scripts/generate-regions.mjs. DO NOT EDIT.

package regions

var supportedRegions = []string{
	"BR1",
	"EUN1",
	"EUW1",
	"JP1",
	"KR",
	"LA1",
	"LA2",
	"ME1",
	"NA1",
	"OC1",
	"PH2",
	"RU",
	"SG2",
	"TH2",
	"TR1",
	"TW2",
	"VN2",
}

var supportedRegionSet = map[string]struct{}{
	"BR1":  {},
	"EUN1": {},
	"EUW1": {},
	"JP1":  {},
	"KR":   {},
	"LA1":  {},
	"LA2":  {},
	"ME1":  {},
	"NA1":  {},
	"OC1":  {},
	"PH2":  {},
	"RU":   {},
	"SG2":  {},
	"TH2":  {},
	"TR1":  {},
	"TW2":  {},
	"VN2":  {},
}

var defaultRegion = "JP1"

var regionPathSegments = map[string]string{
	"BR1":  "br",
	"EUN1": "eune",
	"EUW1": "euw",
	"JP1":  "jp",
	"KR":   "kr",
	"LA1":  "lan",
	"LA2":  "las",
	"ME1":  "me",
	"NA1":  "na",
	"OC1":  "oce",
	"PH2":  "ph",
	"RU":   "ru",
	"SG2":  "sg",
	"TH2":  "th",
	"TR1":  "tr",
	"TW2":  "tw",
	"VN2":  "vn",
}

var pathSegmentRegions = map[string]string{
	"br":   "BR1",
	"eune": "EUN1",
	"euw":  "EUW1",
	"jp":   "JP1",
	"kr":   "KR",
	"lan":  "LA1",
	"las":  "LA2",
	"me":   "ME1",
	"na":   "NA1",
	"oce":  "OC1",
	"ph":   "PH2",
	"ru":   "RU",
	"sg":   "SG2",
	"th":   "TH2",
	"tr":   "TR1",
	"tw":   "TW2",
	"vn":   "VN2",
}

func Names() []string {
	regions := make([]string, len(supportedRegions))
	copy(regions, supportedRegions)
	return regions
}

func IsSupported(name string) bool {
	_, ok := supportedRegionSet[name]
	return ok
}

func Default() string {
	return defaultRegion
}

func PathSegment(name string) (string, bool) {
	segment, ok := regionPathSegments[name]
	return segment, ok
}

func RegionFromPathSegment(segment string) (string, bool) {
	region, ok := pathSegmentRegions[segment]
	return region, ok
}
