// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package db

import (
	"context"
)

const countPlayerLabelVotesByPuuid = `-- name: CountPlayerLabelVotesByPuuid :one
SELECT
  COUNT(*)::bigint AS vote_count
FROM player_label_votes AS plv
JOIN player AS p ON p.id = plv.player_id
WHERE p.puuid = $1
`

func (q *Queries) CountPlayerLabelVotesByPuuid(ctx context.Context, puuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayerLabelVotesByPuuid, puuid)
	var vote_count int64
	err := row.Scan(&vote_count)
	return vote_count, err
}

const getLabelByID = `-- name: GetLabelByID :one
SELECT
  id,
  name,
  created_at,
  updated_at
FROM label
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLabelByID(ctx context.Context, id int16) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByID, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerLabelVoteByPuuidAndVoterKey = `-- name: GetPlayerLabelVoteByPuuidAndVoterKey :one
SELECT
  plv.id,
  plv.player_id,
  plv.label_id,
  plv.voter_key,
  plv.created_at,
  plv.updated_at
FROM player_label_votes AS plv
JOIN player AS p ON p.id = plv.player_id
WHERE p.puuid = $1
  AND plv.voter_key = $2
LIMIT 1
`

type GetPlayerLabelVoteByPuuidAndVoterKeyParams struct {
	Puuid    string `json:"puuid"`
	VoterKey string `json:"voter_key"`
}

func (q *Queries) GetPlayerLabelVoteByPuuidAndVoterKey(ctx context.Context, arg GetPlayerLabelVoteByPuuidAndVoterKeyParams) (PlayerLabelVote, error) {
	row := q.db.QueryRowContext(ctx, getPlayerLabelVoteByPuuidAndVoterKey, arg.Puuid, arg.VoterKey)
	var i PlayerLabelVote
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.LabelID,
		&i.VoterKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT
  id,
  name,
  created_at,
  updated_at
FROM label
ORDER BY id
`

func (q *Queries) ListLabels(ctx context.Context) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerLabelVoteSummariesByPuuid = `-- name: ListPlayerLabelVoteSummariesByPuuid :many
SELECT
  l.id,
  l.name,
  COUNT(*)::bigint AS vote_count
FROM player_label_votes AS plv
JOIN player AS p ON p.id = plv.player_id
JOIN label AS l ON l.id = plv.label_id
WHERE p.puuid = $1
GROUP BY l.id, l.name
ORDER BY vote_count DESC, l.id ASC
`

type ListPlayerLabelVoteSummariesByPuuidRow struct {
	ID        int16  `json:"id"`
	Name      string `json:"name"`
	VoteCount int64  `json:"vote_count"`
}

func (q *Queries) ListPlayerLabelVoteSummariesByPuuid(ctx context.Context, puuid string) ([]ListPlayerLabelVoteSummariesByPuuidRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerLabelVoteSummariesByPuuid, puuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerLabelVoteSummariesByPuuidRow
	for rows.Next() {
		var i ListPlayerLabelVoteSummariesByPuuidRow
		if err := rows.Scan(&i.ID, &i.Name, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopPlayerLabelVoteSummariesByPuuid = `-- name: ListTopPlayerLabelVoteSummariesByPuuid :many
SELECT
  l.id,
  l.name,
  COUNT(*)::bigint AS vote_count
FROM player_label_votes AS plv
JOIN player AS p ON p.id = plv.player_id
JOIN label AS l ON l.id = plv.label_id
WHERE p.puuid = $1
GROUP BY l.id, l.name
ORDER BY vote_count DESC, l.id ASC
LIMIT $2
`

type ListTopPlayerLabelVoteSummariesByPuuidParams struct {
	Puuid      string `json:"puuid"`
	LimitCount int32  `json:"limit_count"`
}

type ListTopPlayerLabelVoteSummariesByPuuidRow struct {
	ID        int16  `json:"id"`
	Name      string `json:"name"`
	VoteCount int64  `json:"vote_count"`
}

func (q *Queries) ListTopPlayerLabelVoteSummariesByPuuid(ctx context.Context, arg ListTopPlayerLabelVoteSummariesByPuuidParams) ([]ListTopPlayerLabelVoteSummariesByPuuidRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopPlayerLabelVoteSummariesByPuuid, arg.Puuid, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopPlayerLabelVoteSummariesByPuuidRow
	for rows.Next() {
		var i ListTopPlayerLabelVoteSummariesByPuuidRow
		if err := rows.Scan(&i.ID, &i.Name, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerLabelVoteByPuuid = `-- name: UpsertPlayerLabelVoteByPuuid :one
INSERT INTO player_label_votes (
  player_id,
  label_id,
  voter_key
)
SELECT
  p.id,
  $1,
  $2
FROM player AS p
WHERE p.puuid = $3
ON CONFLICT (player_id, voter_key) DO UPDATE SET
  label_id = EXCLUDED.label_id,
  updated_at = NOW()
RETURNING
  id,
  player_id,
  label_id,
  voter_key,
  created_at,
  updated_at
`

type UpsertPlayerLabelVoteByPuuidParams struct {
	LabelID  int16  `json:"label_id"`
	VoterKey string `json:"voter_key"`
	Puuid    string `json:"puuid"`
}

func (q *Queries) UpsertPlayerLabelVoteByPuuid(ctx context.Context, arg UpsertPlayerLabelVoteByPuuidParams) (PlayerLabelVote, error) {
	row := q.db.QueryRowContext(ctx, upsertPlayerLabelVoteByPuuid, arg.LabelID, arg.VoterKey, arg.Puuid)
	var i PlayerLabelVote
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.LabelID,
		&i.VoterKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
