// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: masterdata.sql

package db

import (
	"context"
)

const getPlayerRankByTierDivision = `-- name: GetPlayerRankByTierDivision :one
SELECT
  id,
  tier,
  division,
  created_at,
  updated_at
FROM player_ranks
WHERE tier = UPPER(BTRIM($1))
  AND division = UPPER(BTRIM($2))
`

type GetPlayerRankByTierDivisionParams struct {
	Tier     string `json:"tier"`
	Division string `json:"division"`
}

func (q *Queries) GetPlayerRankByTierDivision(ctx context.Context, arg GetPlayerRankByTierDivisionParams) (PlayerRank, error) {
	row := q.db.QueryRowContext(ctx, getPlayerRankByTierDivision, arg.Tier, arg.Division)
	var i PlayerRank
	err := row.Scan(
		&i.ID,
		&i.Tier,
		&i.Division,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegionByName = `-- name: GetRegionByName :one
SELECT
  id,
  name,
  created_at,
  updated_at
FROM region
WHERE name = UPPER(BTRIM($1))
`

func (q *Queries) GetRegionByName(ctx context.Context, name string) (Region, error) {
	row := q.db.QueryRowContext(ctx, getRegionByName, name)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegions = `-- name: ListRegions :many
SELECT
  id,
  name,
  created_at,
  updated_at
FROM region
ORDER BY id
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regionExists = `-- name: RegionExists :one
SELECT EXISTS (
  SELECT 1
  FROM region
  WHERE name = UPPER(BTRIM($1))
) AS exists
`

func (q *Queries) RegionExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, regionExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
