// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listRecentMatchHistoriesByPlayerID = `-- name: ListRecentMatchHistoriesByPlayerID :many
SELECT
  mh.id AS match_history_id,
  mh.match_id,
  mh.region_id,
  mh.queue_id,
  mh.game_mode,
  mh.game_version,
  mh.duration_seconds,
  mh.played_at,
  mh.created_at AS match_history_created_at,
  mh.updated_at AS match_history_updated_at,
  mp.player_id,
  mp.team_id,
  mp.champion_name,
  mp.team_position,
  mp.role,
  mp.win,
  mp.kills,
  mp.deaths,
  mp.assists,
  mp.summoner_spell1_id,
  mp.summoner_spell2_id
FROM match_participant AS mp
JOIN match_history AS mh ON mh.id = mp.match_history_id
WHERE mp.player_id = $1
ORDER BY mh.played_at DESC
LIMIT $2
`

type ListRecentMatchHistoriesByPlayerIDParams struct {
	PlayerID   int64 `json:"player_id"`
	LimitCount int32 `json:"limit_count"`
}

type ListRecentMatchHistoriesByPlayerIDRow struct {
	MatchHistoryID        int64          `json:"match_history_id"`
	MatchID               string         `json:"match_id"`
	RegionID              int16          `json:"region_id"`
	QueueID               int32          `json:"queue_id"`
	GameMode              string         `json:"game_mode"`
	GameVersion           string         `json:"game_version"`
	DurationSeconds       int32          `json:"duration_seconds"`
	PlayedAt              time.Time      `json:"played_at"`
	MatchHistoryCreatedAt time.Time      `json:"match_history_created_at"`
	MatchHistoryUpdatedAt time.Time      `json:"match_history_updated_at"`
	PlayerID              int64          `json:"player_id"`
	TeamID                int16          `json:"team_id"`
	ChampionName          string         `json:"champion_name"`
	TeamPosition          sql.NullString `json:"team_position"`
	Role                  sql.NullString `json:"role"`
	Win                   bool           `json:"win"`
	Kills                 int32          `json:"kills"`
	Deaths                int32          `json:"deaths"`
	Assists               int32          `json:"assists"`
	SummonerSpell1ID      int32          `json:"summoner_spell1_id"`
	SummonerSpell2ID      int32          `json:"summoner_spell2_id"`
}

func (q *Queries) ListRecentMatchHistoriesByPlayerID(ctx context.Context, arg ListRecentMatchHistoriesByPlayerIDParams) ([]ListRecentMatchHistoriesByPlayerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMatchHistoriesByPlayerID, arg.PlayerID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMatchHistoriesByPlayerIDRow
	for rows.Next() {
		var i ListRecentMatchHistoriesByPlayerIDRow
		if err := rows.Scan(
			&i.MatchHistoryID,
			&i.MatchID,
			&i.RegionID,
			&i.QueueID,
			&i.GameMode,
			&i.GameVersion,
			&i.DurationSeconds,
			&i.PlayedAt,
			&i.MatchHistoryCreatedAt,
			&i.MatchHistoryUpdatedAt,
			&i.PlayerID,
			&i.TeamID,
			&i.ChampionName,
			&i.TeamPosition,
			&i.Role,
			&i.Win,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.SummonerSpell1ID,
			&i.SummonerSpell2ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatchHistory = `-- name: UpsertMatchHistory :one
INSERT INTO match_history (
  match_id,
  region_id,
  queue_id,
  game_mode,
  game_version,
  duration_seconds,
  played_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT (match_id) DO UPDATE SET
  region_id = EXCLUDED.region_id,
  queue_id = EXCLUDED.queue_id,
  game_mode = EXCLUDED.game_mode,
  game_version = EXCLUDED.game_version,
  duration_seconds = EXCLUDED.duration_seconds,
  played_at = EXCLUDED.played_at,
  updated_at = NOW()
RETURNING id, match_id, region_id, queue_id, game_mode, game_version, duration_seconds, played_at, created_at, updated_at
`

type UpsertMatchHistoryParams struct {
	MatchID         string    `json:"match_id"`
	RegionID        int16     `json:"region_id"`
	QueueID         int32     `json:"queue_id"`
	GameMode        string    `json:"game_mode"`
	GameVersion     string    `json:"game_version"`
	DurationSeconds int32     `json:"duration_seconds"`
	PlayedAt        time.Time `json:"played_at"`
}

func (q *Queries) UpsertMatchHistory(ctx context.Context, arg UpsertMatchHistoryParams) (MatchHistory, error) {
	row := q.db.QueryRowContext(ctx, upsertMatchHistory,
		arg.MatchID,
		arg.RegionID,
		arg.QueueID,
		arg.GameMode,
		arg.GameVersion,
		arg.DurationSeconds,
		arg.PlayedAt,
	)
	var i MatchHistory
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.RegionID,
		&i.QueueID,
		&i.GameMode,
		&i.GameVersion,
		&i.DurationSeconds,
		&i.PlayedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
