// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_participants.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listMatchParticipantsByMatchHistoryID = `-- name: ListMatchParticipantsByMatchHistoryID :many
SELECT
  mp.match_history_id,
  mp.player_id,
  p.puuid,
  mp.game_name_snapshot,
  mp.tag_line_snapshot,
  mp.team_id,
  mp.champion_name,
  mp.team_position,
  mp.role,
  mp.win,
  mp.kills,
  mp.deaths,
  mp.assists,
  mp.summoner_spell1_id,
  mp.summoner_spell2_id,
  mp.created_at AS match_participant_created_at,
  mp.updated_at AS match_participant_updated_at
FROM match_participant AS mp
JOIN player AS p ON p.id = mp.player_id
WHERE mp.match_history_id = $1
ORDER BY mp.team_id, mp.player_id
`

type ListMatchParticipantsByMatchHistoryIDRow struct {
	MatchHistoryID            int64          `json:"match_history_id"`
	PlayerID                  int64          `json:"player_id"`
	Puuid                     string         `json:"puuid"`
	GameNameSnapshot          sql.NullString `json:"game_name_snapshot"`
	TagLineSnapshot           sql.NullString `json:"tag_line_snapshot"`
	TeamID                    int16          `json:"team_id"`
	ChampionName              string         `json:"champion_name"`
	TeamPosition              sql.NullString `json:"team_position"`
	Role                      sql.NullString `json:"role"`
	Win                       bool           `json:"win"`
	Kills                     int32          `json:"kills"`
	Deaths                    int32          `json:"deaths"`
	Assists                   int32          `json:"assists"`
	SummonerSpell1ID          int32          `json:"summoner_spell1_id"`
	SummonerSpell2ID          int32          `json:"summoner_spell2_id"`
	MatchParticipantCreatedAt time.Time      `json:"match_participant_created_at"`
	MatchParticipantUpdatedAt time.Time      `json:"match_participant_updated_at"`
}

func (q *Queries) ListMatchParticipantsByMatchHistoryID(ctx context.Context, matchHistoryID int64) ([]ListMatchParticipantsByMatchHistoryIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchParticipantsByMatchHistoryID, matchHistoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchParticipantsByMatchHistoryIDRow
	for rows.Next() {
		var i ListMatchParticipantsByMatchHistoryIDRow
		if err := rows.Scan(
			&i.MatchHistoryID,
			&i.PlayerID,
			&i.Puuid,
			&i.GameNameSnapshot,
			&i.TagLineSnapshot,
			&i.TeamID,
			&i.ChampionName,
			&i.TeamPosition,
			&i.Role,
			&i.Win,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.SummonerSpell1ID,
			&i.SummonerSpell2ID,
			&i.MatchParticipantCreatedAt,
			&i.MatchParticipantUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatchParticipant = `-- name: UpsertMatchParticipant :exec
INSERT INTO match_participant (
  match_history_id,
  player_id,
  game_name_snapshot,
  tag_line_snapshot,
  team_id,
  champion_name,
  team_position,
  role,
  win,
  kills,
  deaths,
  assists,
  summoner_spell1_id,
  summoner_spell2_id
) VALUES (
  $1,
  $2,
  NULLIF(BTRIM($3), ''),
  NULLIF(BTRIM($4), ''),
  $5,
  $6,
  NULLIF(BTRIM($7), ''),
  NULLIF(BTRIM($8), ''),
  $9,
  $10,
  $11,
  $12,
  $13,
  $14
)
ON CONFLICT (match_history_id, player_id) DO UPDATE SET
  game_name_snapshot = EXCLUDED.game_name_snapshot,
  tag_line_snapshot = EXCLUDED.tag_line_snapshot,
  team_id = EXCLUDED.team_id,
  champion_name = EXCLUDED.champion_name,
  team_position = EXCLUDED.team_position,
  role = EXCLUDED.role,
  win = EXCLUDED.win,
  kills = EXCLUDED.kills,
  deaths = EXCLUDED.deaths,
  assists = EXCLUDED.assists,
  summoner_spell1_id = EXCLUDED.summoner_spell1_id,
  summoner_spell2_id = EXCLUDED.summoner_spell2_id,
  updated_at = NOW()
`

type UpsertMatchParticipantParams struct {
	MatchHistoryID   int64  `json:"match_history_id"`
	PlayerID         int64  `json:"player_id"`
	GameNameSnapshot string `json:"game_name_snapshot"`
	TagLineSnapshot  string `json:"tag_line_snapshot"`
	TeamID           int16  `json:"team_id"`
	ChampionName     string `json:"champion_name"`
	TeamPosition     string `json:"team_position"`
	Role             string `json:"role"`
	Win              bool   `json:"win"`
	Kills            int32  `json:"kills"`
	Deaths           int32  `json:"deaths"`
	Assists          int32  `json:"assists"`
	SummonerSpell1ID int32  `json:"summoner_spell1_id"`
	SummonerSpell2ID int32  `json:"summoner_spell2_id"`
}

func (q *Queries) UpsertMatchParticipant(ctx context.Context, arg UpsertMatchParticipantParams) error {
	_, err := q.db.ExecContext(ctx, upsertMatchParticipant,
		arg.MatchHistoryID,
		arg.PlayerID,
		arg.GameNameSnapshot,
		arg.TagLineSnapshot,
		arg.TeamID,
		arg.ChampionName,
		arg.TeamPosition,
		arg.Role,
		arg.Win,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.SummonerSpell1ID,
		arg.SummonerSpell2ID,
	)
	return err
}
