// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getSavedPlayerByPuuid = `-- name: GetSavedPlayerByPuuid :one
SELECT
  p.id AS player_id,
  p.puuid,
  p.game_name,
  p.tag_line,
  p.region_id,
  r.name AS region_name,
  p.profile_icon_id,
  p.summoner_level,
  p.revision_date,
  p.last_synced_at,
  p.created_at AS player_created_at,
  p.updated_at AS player_updated_at
FROM player AS p
JOIN region AS r ON r.id = p.region_id
WHERE p.puuid = $1
LIMIT 1
`

type GetSavedPlayerByPuuidRow struct {
	PlayerID        int64          `json:"player_id"`
	Puuid           string         `json:"puuid"`
	GameName        sql.NullString `json:"game_name"`
	TagLine         sql.NullString `json:"tag_line"`
	RegionID        int16          `json:"region_id"`
	RegionName      string         `json:"region_name"`
	ProfileIconID   sql.NullInt32  `json:"profile_icon_id"`
	SummonerLevel   sql.NullInt64  `json:"summoner_level"`
	RevisionDate    sql.NullTime   `json:"revision_date"`
	LastSyncedAt    sql.NullTime   `json:"last_synced_at"`
	PlayerCreatedAt time.Time      `json:"player_created_at"`
	PlayerUpdatedAt time.Time      `json:"player_updated_at"`
}

func (q *Queries) GetSavedPlayerByPuuid(ctx context.Context, puuid string) (GetSavedPlayerByPuuidRow, error) {
	row := q.db.QueryRowContext(ctx, getSavedPlayerByPuuid, puuid)
	var i GetSavedPlayerByPuuidRow
	err := row.Scan(
		&i.PlayerID,
		&i.Puuid,
		&i.GameName,
		&i.TagLine,
		&i.RegionID,
		&i.RegionName,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.RevisionDate,
		&i.LastSyncedAt,
		&i.PlayerCreatedAt,
		&i.PlayerUpdatedAt,
	)
	return i, err
}

const getSavedPlayerKeyByRiotID = `-- name: GetSavedPlayerKeyByRiotID :one
SELECT
  p.id AS player_id,
  p.puuid
FROM player AS p
WHERE p.region_id = $1
  AND p.game_name = $2
  AND p.tag_line = $3
LIMIT 1
`

type GetSavedPlayerKeyByRiotIDParams struct {
	RegionID int16          `json:"region_id"`
	GameName sql.NullString `json:"game_name"`
	TagLine  sql.NullString `json:"tag_line"`
}

type GetSavedPlayerKeyByRiotIDRow struct {
	PlayerID int64  `json:"player_id"`
	Puuid    string `json:"puuid"`
}

func (q *Queries) GetSavedPlayerKeyByRiotID(ctx context.Context, arg GetSavedPlayerKeyByRiotIDParams) (GetSavedPlayerKeyByRiotIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSavedPlayerKeyByRiotID, arg.RegionID, arg.GameName, arg.TagLine)
	var i GetSavedPlayerKeyByRiotIDRow
	err := row.Scan(&i.PlayerID, &i.Puuid)
	return i, err
}

const upsertParticipantPlayer = `-- name: UpsertParticipantPlayer :one
INSERT INTO player (
  puuid,
  game_name,
  tag_line,
  region_id
) VALUES (
  $1,
  NULLIF(BTRIM($2), ''),
  NULLIF(BTRIM($3), ''),
  $4
)
ON CONFLICT (puuid) DO UPDATE SET
  game_name = COALESCE(EXCLUDED.game_name, player.game_name),
  tag_line = COALESCE(EXCLUDED.tag_line, player.tag_line),
  region_id = EXCLUDED.region_id,
  updated_at = NOW()
RETURNING id, puuid, game_name, tag_line, region_id, profile_icon_id, summoner_level, revision_date, last_synced_at, created_at, updated_at
`

type UpsertParticipantPlayerParams struct {
	Puuid    string `json:"puuid"`
	GameName string `json:"game_name"`
	TagLine  string `json:"tag_line"`
	RegionID int16  `json:"region_id"`
}

func (q *Queries) UpsertParticipantPlayer(ctx context.Context, arg UpsertParticipantPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, upsertParticipantPlayer,
		arg.Puuid,
		arg.GameName,
		arg.TagLine,
		arg.RegionID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Puuid,
		&i.GameName,
		&i.TagLine,
		&i.RegionID,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.RevisionDate,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlayerProfile = `-- name: UpsertPlayerProfile :one
INSERT INTO player (
  puuid,
  game_name,
  tag_line,
  region_id,
  profile_icon_id,
  summoner_level,
  revision_date,
  last_synced_at
) VALUES (
  $1,
  NULLIF(BTRIM($2), ''),
  NULLIF(BTRIM($3), ''),
  $4,
  $5,
  $6,
  $7,
  NOW()
)
ON CONFLICT (puuid) DO UPDATE SET
  game_name = EXCLUDED.game_name,
  tag_line = EXCLUDED.tag_line,
  region_id = EXCLUDED.region_id,
  profile_icon_id = EXCLUDED.profile_icon_id,
  summoner_level = EXCLUDED.summoner_level,
  revision_date = EXCLUDED.revision_date,
  last_synced_at = EXCLUDED.last_synced_at,
  updated_at = NOW()
RETURNING id, puuid, game_name, tag_line, region_id, profile_icon_id, summoner_level, revision_date, last_synced_at, created_at, updated_at
`

type UpsertPlayerProfileParams struct {
	Puuid         string        `json:"puuid"`
	GameName      string        `json:"game_name"`
	TagLine       string        `json:"tag_line"`
	RegionID      int16         `json:"region_id"`
	ProfileIconID sql.NullInt32 `json:"profile_icon_id"`
	SummonerLevel sql.NullInt64 `json:"summoner_level"`
	RevisionDate  sql.NullTime  `json:"revision_date"`
}

func (q *Queries) UpsertPlayerProfile(ctx context.Context, arg UpsertPlayerProfileParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, upsertPlayerProfile,
		arg.Puuid,
		arg.GameName,
		arg.TagLine,
		arg.RegionID,
		arg.ProfileIconID,
		arg.SummonerLevel,
		arg.RevisionDate,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Puuid,
		&i.GameName,
		&i.TagLine,
		&i.RegionID,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.RevisionDate,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
