// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_ranks.sql

package db

import (
	"context"
)

const getPlayerRankByTierDivision = `-- name: GetPlayerRankByTierDivision :one
SELECT
  id,
  tier,
  division,
  created_at,
  updated_at
FROM player_ranks
WHERE tier = $1
  AND division = $2
`

type GetPlayerRankByTierDivisionParams struct {
	Tier     string `json:"tier"`
	Division string `json:"division"`
}

func (q *Queries) GetPlayerRankByTierDivision(ctx context.Context, arg GetPlayerRankByTierDivisionParams) (PlayerRank, error) {
	row := q.db.QueryRowContext(ctx, getPlayerRankByTierDivision, arg.Tier, arg.Division)
	var i PlayerRank
	err := row.Scan(
		&i.ID,
		&i.Tier,
		&i.Division,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
