// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_current_ranks.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deletePlayerCurrentRanksByPlayerID = `-- name: DeletePlayerCurrentRanksByPlayerID :exec
DELETE FROM player_current_rank
WHERE player_id = $1
`

func (q *Queries) DeletePlayerCurrentRanksByPlayerID(ctx context.Context, playerID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerCurrentRanksByPlayerID, playerID)
	return err
}

const listPlayerCurrentRanksByPlayerID = `-- name: ListPlayerCurrentRanksByPlayerID :many
SELECT
  pcr.player_id,
  pcr.queue_type,
  pcr.player_ranks_id,
  pr.tier,
  pr.division,
  pcr.league_points,
  pcr.wins,
  pcr.losses,
  pcr.recorded_at,
  pcr.created_at AS player_current_rank_created_at,
  pcr.updated_at AS player_current_rank_updated_at
FROM player_current_rank AS pcr
JOIN player_ranks AS pr ON pr.id = pcr.player_ranks_id
WHERE pcr.player_id = $1
ORDER BY
  CASE pcr.queue_type
    WHEN 'RANKED_SOLO_5x5' THEN 1
    WHEN 'RANKED_FLEX_SR' THEN 2
    ELSE 3
  END,
  pcr.queue_type
`

type ListPlayerCurrentRanksByPlayerIDRow struct {
	PlayerID                   int64         `json:"player_id"`
	QueueType                  string        `json:"queue_type"`
	PlayerRanksID              sql.NullInt16 `json:"player_ranks_id"`
	Tier                       string        `json:"tier"`
	Division                   string        `json:"division"`
	LeaguePoints               sql.NullInt32 `json:"league_points"`
	Wins                       sql.NullInt32 `json:"wins"`
	Losses                     sql.NullInt32 `json:"losses"`
	RecordedAt                 time.Time     `json:"recorded_at"`
	PlayerCurrentRankCreatedAt time.Time     `json:"player_current_rank_created_at"`
	PlayerCurrentRankUpdatedAt time.Time     `json:"player_current_rank_updated_at"`
}

func (q *Queries) ListPlayerCurrentRanksByPlayerID(ctx context.Context, playerID int64) ([]ListPlayerCurrentRanksByPlayerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerCurrentRanksByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerCurrentRanksByPlayerIDRow
	for rows.Next() {
		var i ListPlayerCurrentRanksByPlayerIDRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.QueueType,
			&i.PlayerRanksID,
			&i.Tier,
			&i.Division,
			&i.LeaguePoints,
			&i.Wins,
			&i.Losses,
			&i.RecordedAt,
			&i.PlayerCurrentRankCreatedAt,
			&i.PlayerCurrentRankUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerCurrentRank = `-- name: UpsertPlayerCurrentRank :exec
INSERT INTO player_current_rank (
  player_id,
  queue_type,
  player_ranks_id,
  league_points,
  wins,
  losses,
  recorded_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT (player_id, queue_type) DO UPDATE SET
  player_ranks_id = EXCLUDED.player_ranks_id,
  league_points = EXCLUDED.league_points,
  wins = EXCLUDED.wins,
  losses = EXCLUDED.losses,
  recorded_at = EXCLUDED.recorded_at,
  updated_at = NOW()
`

type UpsertPlayerCurrentRankParams struct {
	PlayerID      int64         `json:"player_id"`
	QueueType     string        `json:"queue_type"`
	PlayerRanksID sql.NullInt16 `json:"player_ranks_id"`
	LeaguePoints  sql.NullInt32 `json:"league_points"`
	Wins          sql.NullInt32 `json:"wins"`
	Losses        sql.NullInt32 `json:"losses"`
	RecordedAt    time.Time     `json:"recorded_at"`
}

func (q *Queries) UpsertPlayerCurrentRank(ctx context.Context, arg UpsertPlayerCurrentRankParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerCurrentRank,
		arg.PlayerID,
		arg.QueueType,
		arg.PlayerRanksID,
		arg.LeaguePoints,
		arg.Wins,
		arg.Losses,
		arg.RecordedAt,
	)
	return err
}
