-- +goose Up
INSERT INTO region (name) VALUES
  ('BR1'),
  ('EUN1'),
  ('EUW1'),
  ('JP1'),
  ('KR'),
  ('LA1'),
  ('LA2'),
  ('ME1'),
  ('NA1'),
  ('OC1'),
  ('PH2'),
  ('RU'),
  ('SG2'),
  ('TH2'),
  ('TR1'),
  ('TW2'),
  ('VN2')
ON CONFLICT (name) DO NOTHING;

INSERT INTO player_ranks (tier, division) VALUES
  ('IRON', 'IV'),
  ('IRON', 'III'),
  ('IRON', 'II'),
  ('IRON', 'I'),
  ('BRONZE', 'IV'),
  ('BRONZE', 'III'),
  ('BRONZE', 'II'),
  ('BRONZE', 'I'),
  ('SILVER', 'IV'),
  ('SILVER', 'III'),
  ('SILVER', 'II'),
  ('SILVER', 'I'),
  ('GOLD', 'IV'),
  ('GOLD', 'III'),
  ('GOLD', 'II'),
  ('GOLD', 'I'),
  ('PLATINUM', 'IV'),
  ('PLATINUM', 'III'),
  ('PLATINUM', 'II'),
  ('PLATINUM', 'I'),
  ('EMERALD', 'IV'),
  ('EMERALD', 'III'),
  ('EMERALD', 'II'),
  ('EMERALD', 'I'),
  ('DIAMOND', 'IV'),
  ('DIAMOND', 'III'),
  ('DIAMOND', 'II'),
  ('DIAMOND', 'I'),
  ('MASTER', 'I'),
  ('GRANDMASTER', 'I'),
  ('CHALLENGER', 'I')
ON CONFLICT (tier, division) DO NOTHING;

-- +goose Down
DELETE FROM player_ranks
WHERE (tier, division) IN (
  ('IRON', 'IV'),
  ('IRON', 'III'),
  ('IRON', 'II'),
  ('IRON', 'I'),
  ('BRONZE', 'IV'),
  ('BRONZE', 'III'),
  ('BRONZE', 'II'),
  ('BRONZE', 'I'),
  ('SILVER', 'IV'),
  ('SILVER', 'III'),
  ('SILVER', 'II'),
  ('SILVER', 'I'),
  ('GOLD', 'IV'),
  ('GOLD', 'III'),
  ('GOLD', 'II'),
  ('GOLD', 'I'),
  ('PLATINUM', 'IV'),
  ('PLATINUM', 'III'),
  ('PLATINUM', 'II'),
  ('PLATINUM', 'I'),
  ('EMERALD', 'IV'),
  ('EMERALD', 'III'),
  ('EMERALD', 'II'),
  ('EMERALD', 'I'),
  ('DIAMOND', 'IV'),
  ('DIAMOND', 'III'),
  ('DIAMOND', 'II'),
  ('DIAMOND', 'I'),
  ('MASTER', 'I'),
  ('GRANDMASTER', 'I'),
  ('CHALLENGER', 'I')
);

DELETE FROM region
WHERE name IN (
  'BR1',
  'EUN1',
  'EUW1',
  'JP1',
  'KR',
  'LA1',
  'LA2',
  'ME1',
  'NA1',
  'OC1',
  'PH2',
  'RU',
  'SG2',
  'TH2',
  'TR1',
  'TW2',
  'VN2'
);
