import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const repoRoot = process.cwd();
const jsonPath = path.join(repoRoot, "shared", "regions.json");
const frontendOutputPath = path.join(repoRoot, "frontend", "lib", "regions.generated.ts");
const backendOutputPath = path.join(
  repoRoot,
  "backend",
  "internal",
  "domain",
  "regions",
  "generated.go",
);

/**
 * @typedef {{
 *   defaultRegion: string,
 *   regions: string[],
 *   pathSegments: Record<string, string>,
 * }} RegionsConfig
 */

/** @type {RegionsConfig} */
const regionsConfig = JSON.parse(fs.readFileSync(jsonPath, "utf8"));

validateConfig(regionsConfig);

const frontendOutput = generateFrontendOutput(regionsConfig);
const backendOutput = generateBackendOutput(regionsConfig);

fs.writeFileSync(frontendOutputPath, frontendOutput);
fs.writeFileSync(backendOutputPath, backendOutput);

function validateConfig(config) {
  if (!config.regions.includes(config.defaultRegion)) {
    throw new Error(`defaultRegion ${config.defaultRegion} is not in regions`);
  }

  for (const region of config.regions) {
    if (!(region in config.pathSegments)) {
      throw new Error(`missing path segment for region ${region}`);
    }
  }

  const seenPathSegments = new Set();
  for (const [region, segment] of Object.entries(config.pathSegments)) {
    if (!config.regions.includes(region)) {
      throw new Error(`path segment configured for unsupported region ${region}`);
    }
    if (seenPathSegments.has(segment)) {
      throw new Error(`duplicate path segment ${segment}`);
    }
    seenPathSegments.add(segment);
  }
}

function quote(value) {
  return JSON.stringify(value);
}

function generateFrontendOutput(config) {
  const supportedRegions = config.regions
    .map((region) => `  ${quote(region)},`)
    .join("\n");
  const regionPathSegments = config.regions
    .map((region) => `  ${region}: ${quote(config.pathSegments[region])},`)
    .join("\n");
  const pathSegmentRegions = config.regions
    .map((region) => `  ${quote(config.pathSegments[region])}: ${quote(region)},`)
    .join("\n");

  return `// Code generated by scripts/generate-regions.mjs. DO NOT EDIT.

export const SUPPORTED_REGIONS = [
${supportedRegions}
] as const;

export type Region = (typeof SUPPORTED_REGIONS)[number];

export const DEFAULT_REGION: Region = ${quote(config.defaultRegion)};

export const REGION_PATH_SEGMENTS: Record<Region, string> = {
${regionPathSegments}
};

export const PATH_SEGMENT_REGIONS: Record<string, Region> = {
${pathSegmentRegions}
};
`;
}

function generateBackendOutput(config) {
  const supportedRegions = config.regions
    .map((region) => `\t${quote(region)},`)
    .join("\n");
  const supportedRegionSet = config.regions
    .map((region) => `\t${quote(region)}: {},`)
    .join("\n");
  const regionPathSegments = config.regions
    .map((region) => `\t${quote(region)}: ${quote(config.pathSegments[region])},`)
    .join("\n");
  const pathSegmentRegions = config.regions
    .map((region) => `\t${quote(config.pathSegments[region])}: ${quote(region)},`)
    .join("\n");

  return `// Code generated by scripts/generate-regions.mjs. DO NOT EDIT.

package regions

var supportedRegions = []string{
${supportedRegions}
}

var supportedRegionSet = map[string]struct{}{
${supportedRegionSet}
}

var defaultRegion = ${quote(config.defaultRegion)}

var regionPathSegments = map[string]string{
${regionPathSegments}
}

var pathSegmentRegions = map[string]string{
${pathSegmentRegions}
}

func Names() []string {
\tregions := make([]string, len(supportedRegions))
\tcopy(regions, supportedRegions)
\treturn regions
}

func IsSupported(name string) bool {
\t_, ok := supportedRegionSet[name]
\treturn ok
}

func Default() string {
\treturn defaultRegion
}

func PathSegment(name string) (string, bool) {
\tsegment, ok := regionPathSegments[name]
\treturn segment, ok
}

func RegionFromPathSegment(segment string) (string, bool) {
\tregion, ok := pathSegmentRegions[segment]
\treturn region, ok
}
`;
}
