// Code generated by scripts/generate-regions.mjs. DO NOT EDIT.

export const SUPPORTED_REGIONS = [
  "BR1",
  "EUN1",
  "EUW1",
  "JP1",
  "KR",
  "LA1",
  "LA2",
  "ME1",
  "NA1",
  "OC1",
  "PH2",
  "RU",
  "SG2",
  "TH2",
  "TR1",
  "TW2",
  "VN2",
] as const;

export type Region = (typeof SUPPORTED_REGIONS)[number];

export const DEFAULT_REGION: Region = "JP1";

export const REGION_PATH_SEGMENTS: Record<Region, string> = {
  BR1: "br",
  EUN1: "eune",
  EUW1: "euw",
  JP1: "jp",
  KR: "kr",
  LA1: "lan",
  LA2: "las",
  ME1: "me",
  NA1: "na",
  OC1: "oce",
  PH2: "ph",
  RU: "ru",
  SG2: "sg",
  TH2: "th",
  TR1: "tr",
  TW2: "tw",
  VN2: "vn",
};

export const PATH_SEGMENT_REGIONS: Record<string, Region> = {
  "br": "BR1",
  "eune": "EUN1",
  "euw": "EUW1",
  "jp": "JP1",
  "kr": "KR",
  "lan": "LA1",
  "las": "LA2",
  "me": "ME1",
  "na": "NA1",
  "oce": "OC1",
  "ph": "PH2",
  "ru": "RU",
  "sg": "SG2",
  "th": "TH2",
  "tr": "TR1",
  "tw": "TW2",
  "vn": "VN2",
};
